package processor

type EntityMemories struct {
	Memory []float64
	Input  []float64
}

func (p *Processor) initMemories() {
	p.memories = make(map[int][]float64)
	p.memories[0] = make([]float64, 4096)                                    // Level Memory
	p.memories[1] = make([]float64, 4096)                                    // Level Data
	p.memories[2] = make([]float64, len(p.data.EngineConfiguration.Options)) // []Level Option
	p.memories[3] = make([]float64, 16)                                      // Level Transform
	p.memories[4] = make([]float64, 16)                                      // Level Background
	p.memories[5] = make([]float64, 80)                                      // Level UI
	p.memories[6] = make([]float64, 6*len(p.data.EngineData.Buckets))        // []Level Bucket
	p.memories[7] = make([]float64, 12)                                      // Level Score
	p.memories[8] = make([]float64, 6)                                       // Level Life
	p.memories[9] = make([]float64, 10)                                      // Level UI Configuration
	p.memories[10] = make([]float64, 32*len(p.data.LevelData.Entities))      // []Entity Info
	p.memories[11] = make([]float64, 32*len(p.data.LevelData.Entities))      // []Entity Data
	p.memories[12] = make([]float64, 32*len(p.data.LevelData.Entities))      // []Entity Shared Memory
	p.memories[20] = make([]float64, 3)                                      // Entity Info
	p.memories[21] = make([]float64, 32)                                     // Entity Memory
	p.memories[22] = make([]float64, 32)                                     // Entity Data
	p.memories[23] = make([]float64, 4)                                      // Entity Input
	p.memories[24] = make([]float64, 32)                                     // Entity Shared Memory
	p.memories[30] = make([]float64, 3*len(p.data.EngineData.Archetypes))    // []Archetype Life

	rom := make([]float64, len(p.data.EngineRom))
	for i, value := range p.data.EngineRom {
		rom[i] = float64(value)
	}
	p.memories[50] = rom // Engine Rom

	p.memories[100] = make([]float64, 4096) // Temporary Memory
	p.memories[101] = make([]float64, 15)   // Temporary Data

	p.memories[1][2] = p.config.AspectRatio
	p.EntityMemories = map[int]EntityMemories{}
	for entityIndex := range p.data.LevelData.Entities {
		p.EntityMemories[entityIndex] = EntityMemories{
			Memory: make([]float64, 32),
			Input:  make([]float64, 4),
		}
	}
}

func (p *Processor) prepareMemory(entityIndex int, status Status) {
	for i := range p.memories[20] {
		p.memories[20][i] = 0
	}
	p.memories[21] = p.EntityMemories[entityIndex].Memory
	p.memories[23] = p.EntityMemories[entityIndex].Input
	switch status {
	case StatusPreprocess:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = true
		p.memoryWritePermissions[1] = true
		p.memoryWritePermissions[2] = true
		p.memoryWritePermissions[3] = true
		p.memoryWritePermissions[4] = true
		p.memoryWritePermissions[5] = true
		p.memoryWritePermissions[6] = true
		p.memoryWritePermissions[7] = true
		p.memoryWritePermissions[8] = true
		p.memoryWritePermissions[9] = true
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = true
		p.memoryWritePermissions[12] = true
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = true
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = true
		p.memoryWritePermissions[30] = true
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusSpawnOrder:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = false
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = false
		p.memoryWritePermissions[4] = false
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = false
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = false
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusShouldSpawn:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = false
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = false
		p.memoryWritePermissions[4] = false
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = false
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = false
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusInitialize:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = false
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = false
		p.memoryWritePermissions[4] = false
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = false
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = false
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusUpdateSequential:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = true
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = true
		p.memoryWritePermissions[4] = true
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = true
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = true
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusTouch:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = true
		p.memoryWritePermissions[0] = true
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = true
		p.memoryWritePermissions[4] = true
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = true
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = true
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusUpdateParallel:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = false
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = false
		p.memoryWritePermissions[4] = false
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = false
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = false
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	case StatusTerminate:
		p.memoryReadPermissions[0] = true
		p.memoryReadPermissions[1] = true
		p.memoryReadPermissions[2] = true
		p.memoryReadPermissions[3] = true
		p.memoryReadPermissions[4] = true
		p.memoryReadPermissions[5] = true
		p.memoryReadPermissions[6] = true
		p.memoryReadPermissions[7] = true
		p.memoryReadPermissions[8] = true
		p.memoryReadPermissions[9] = true
		p.memoryReadPermissions[10] = true
		p.memoryReadPermissions[11] = true
		p.memoryReadPermissions[12] = true
		p.memoryReadPermissions[20] = true
		p.memoryReadPermissions[21] = true
		p.memoryReadPermissions[22] = true
		p.memoryReadPermissions[23] = true
		p.memoryReadPermissions[24] = true
		p.memoryReadPermissions[30] = true
		p.memoryReadPermissions[50] = true
		p.memoryReadPermissions[100] = true
		p.memoryReadPermissions[101] = false
		p.memoryWritePermissions[0] = false
		p.memoryWritePermissions[1] = false
		p.memoryWritePermissions[2] = false
		p.memoryWritePermissions[3] = false
		p.memoryWritePermissions[4] = false
		p.memoryWritePermissions[5] = false
		p.memoryWritePermissions[6] = false
		p.memoryWritePermissions[7] = false
		p.memoryWritePermissions[8] = false
		p.memoryWritePermissions[9] = false
		p.memoryWritePermissions[10] = false
		p.memoryWritePermissions[11] = false
		p.memoryWritePermissions[12] = false
		p.memoryWritePermissions[20] = false
		p.memoryWritePermissions[21] = true
		p.memoryWritePermissions[22] = false
		p.memoryWritePermissions[23] = true
		p.memoryWritePermissions[24] = false
		p.memoryWritePermissions[30] = false
		p.memoryWritePermissions[50] = false
		p.memoryWritePermissions[100] = true
		p.memoryWritePermissions[101] = false
	default:
		panic("unknown status")
	}
}
